client localhost {
    ipaddr      = 127.0.0.1
    secret      = "$ENV{RADIUS_SHARED_SECRET}"
    require_message_authenticator = yes
    shortname   = localhost
    nastype     = other
}

client docker_network {
    ipaddr      = 172.0.0.0/8
    secret      = "$ENV{RADIUS_SHARED_SECRET}"
    require_message_authenticator = yes
    shortname   = docker
    nastype     = other
}
